# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x99\x01\n\x08TestData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\'\n\x07message\x18\x05 \x01(\x0b\x32\x16.google.protobuf.EmptyB\x07\n\x05_name\"\'\n\x0cRepeatedData\x12\x17\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\t.TestData2\x8e\x01\n\x04Test\x12\x1c\n\x04\x45\x63ho\x12\t.TestData\x1a\t.TestData\x12>\n\x0cRequestEmpty\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12(\n\x08Repeated\x12\r.RepeatedData\x1a\r.RepeatedDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTDATA']._serialized_start=107
  _globals['_TESTDATA']._serialized_end=260
  _globals['_REPEATEDDATA']._serialized_start=262
  _globals['_REPEATEDDATA']._serialized_end=301
  _globals['_TEST']._serialized_start=304
  _globals['_TEST']._serialized_end=446
# @@protoc_insertion_point(module_scope)
