# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x06worker\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0emessages.proto\"\'\n\x12StartWorkerRequest\x12\x11\n\ttask_path\x18\x01 \x01(\t2\xc6\x01\n\x06Worker\x12;\n\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x16.messages.WorkerStatus\x12\x41\n\x0bStartWorker\x12\x1a.worker.StartWorkerRequest\x1a\x16.google.protobuf.Empty\x12<\n\nStopWorker\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTWORKERREQUEST']._serialized_start=69
  _globals['_STARTWORKERREQUEST']._serialized_end=108
  _globals['_WORKER']._serialized_start=111
  _globals['_WORKER']._serialized_end=309
# @@protoc_insertion_point(module_scope)
