# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker_cluster.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'worker_cluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import messages_pb2 as messages__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14worker_cluster.proto\x12\x0eworker_cluster\x1a\x0emessages.proto\x1a\x1bgoogle/protobuf/empty.proto\"D\n\x18GetWorkersStatusResponse\x12(\n\x08statuses\x18\x01 \x03(\x0b\x32\x16.messages.WorkerStatus\"+\n\x16GetWorkerStatusRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"\x1e\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\x1f\n\x0f\x43heckInResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"=\n\x13ReportStatusRequest\x12&\n\x06status\x18\x02 \x01(\x0b\x32\x16.messages.WorkerStatus\"j\n\x1bReportTrainingStatusRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12-\n\x06status\x18\x02 \x01(\x0b\x32\x18.messages.TrainingStatusH\x00\x88\x01\x01\x42\t\n\x07_status2\xa1\x03\n\x15WorkerClusterTraining\x12T\n\x10GetWorkersStatus\x12\x16.google.protobuf.Empty\x1a(.worker_cluster.GetWorkersStatusResponse\x12Q\n\x0fGetWorkerStatus\x12&.worker_cluster.GetWorkerStatusRequest\x1a\x16.messages.WorkerStatus\x12I\n\x12\x41ssignTrainingTask\x12\x1b.worker_cluster.TaskRequest\x1a\x16.messages.WorkerStatus\x12J\n\x11GetTrainingStatus\x12\x1b.worker_cluster.TaskRequest\x1a\x18.messages.TrainingStatus\x12H\n\x11PauseTrainingTask\x12\x1b.worker_cluster.TaskRequest\x1a\x16.google.protobuf.Empty2\x81\x02\n\x13WorkerClusterWorker\x12@\n\x07\x43heckIn\x12\x14.messages.WorkerData\x1a\x1f.worker_cluster.CheckInResponse\x12K\n\x0cReportStatus\x12#.worker_cluster.ReportStatusRequest\x1a\x16.google.protobuf.Empty\x12[\n\x14ReportTrainingStatus\x12+.worker_cluster.ReportTrainingStatusRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_cluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETWORKERSSTATUSRESPONSE']._serialized_start=85
  _globals['_GETWORKERSSTATUSRESPONSE']._serialized_end=153
  _globals['_GETWORKERSTATUSREQUEST']._serialized_start=155
  _globals['_GETWORKERSTATUSREQUEST']._serialized_end=198
  _globals['_TASKREQUEST']._serialized_start=200
  _globals['_TASKREQUEST']._serialized_end=230
  _globals['_CHECKINRESPONSE']._serialized_start=232
  _globals['_CHECKINRESPONSE']._serialized_end=263
  _globals['_REPORTSTATUSREQUEST']._serialized_start=265
  _globals['_REPORTSTATUSREQUEST']._serialized_end=326
  _globals['_REPORTTRAININGSTATUSREQUEST']._serialized_start=328
  _globals['_REPORTTRAININGSTATUSREQUEST']._serialized_end=434
  _globals['_WORKERCLUSTERTRAINING']._serialized_start=437
  _globals['_WORKERCLUSTERTRAINING']._serialized_end=854
  _globals['_WORKERCLUSTERWORKER']._serialized_start=857
  _globals['_WORKERCLUSTERWORKER']._serialized_end=1114
# @@protoc_insertion_point(module_scope)
